### ISSUE TITLE
How can I mix with mongofb?

### ISSUE THREAD

**Issue by katopz** [glittershark/meteor-express#1]
Hi @glittershark 

I want to sync Firebase with mongodb which use by Meteor.
Far as I know this https://github.com/scien/mongofb use express.
It's working but not with Meteor yet. And your lib support express via Meteor.

So the question is it suppose to be `meteor-express-mongofb` to make it work.(and how to mix it?)
or maybe there is some other (shorter) way around to accomplish this?

Thanks!

**Comment by glittershark** [comment]
Same way you'd do Express middleware normally
